roi_names = {
    'rL_AI.csv': 'Left Ant. Insula',	
    'rL_aMFG.csv': 'Left aMFG',
    'rL_FEF.csv': 'Left FEF',	
    'rL_IPS.csv': 'Left IPS',	
    'rL_mMFG.csv': 'Left mMFG',	
    'rL_pMFG.csv': 'Left pMFG',
    'rL_preSMA.csv': 'Left preSMA',	
    'rL_ESV.csv': 'Left ESV',
    'rR_AI.csv': 'Right Ant. Insula',	
    'rR_aMFG.csv': 'Right aMFG',
    'rR_FEF.csv': 'Right FEF',	
    'rR_IPS.csv': 'Right IPS',	
    'rR_mMFG.csv': 'Right mMFG',	
    'rR_pMFG.csv': 'Right pMFG',	
    'rR_preSMA.csv': 'Right preSMA',	
    'rR_ESV.csv': 'Right ESV',
    'rR_TPJ.csv': 'Right TPJ',	
    #'rR_TempP.csv': 'Right Temporal\n Pole',	
    'rR_Rsp.csv': 'Right RSP',	
    'rR_pIPL.csv': 'Right IPL',	
    'rR_PHC.csv': 'Right PHC',	
    'rR_PCC.csv': 'Right PCC',	
    'rR_LTC.csv': 'Right LTC',	
    'rR_HF.csv': 'Right HF',	
    'rR_aMPFC.csv': 'Right aMPFC',	
    'rL_TPJ.csv': 'Left TPJ',	
    #'rL_TempP.csv': 'Left Temporal\n Pole',	
    'rL_Rsp.csv': 'Left RSP',	
    'rL_pIPL.csv': 'Left pIPL',	
    'rL_PHC.csv': 'Left PHC',	
    'rL_PCC.csv': 'Left PCC',	
    'rL_LTC.csv': 'Left LTC',	
    'rL_HF.csv': 'Left HF',	
    'rL_aMPFC.csv': 'Left aMPFC',	
    'rvMPFC.csv': 'vMPFC',	
    'rdMPFC.csv': 'dMPFC',	
    'rAuditory_Te3.csv': 'Auditory Cortex',
    'rLeft_Auditory_STS1.csv': 'Left Audtry STS',
    'rLeft_Auditory_Te10.csv': 'Left Audtry Te10',
    'rLeft_Auditory_Te11.csv': 'Left Audtry Te11',
    'rLeft_Auditory_Te12.csv': 'Left Audtry 12',
    'rLeft_Broca_44.csv': 'Left Broca 44',
    'rLeft_Broca_45.csv': 'Left Broca 45',
    'rLeft_Motor_4a.csv': 'Left Motor 4a',
    'rLeft_Motor_4p.csv': 'Left Motor 4p',
    'rLeft_PSC_1.csv': 'Left PSC',
    'rLeft_PSC_3a.csv': 'Left PSC 3a',
    'rLeft_PSC_3b.csv': 'Left PSC 3b',
    'rRight_Auditory_STS1.csv': 'Right Audtry STS',
    'rRight_Auditory_Te10.csv': 'Right Audtry Te10',
    'rRight_Auditory_Te11.csv': 'Right Audtry Te11',
    'rRight_Auditory_Te12.csv': 'Right Audtry Te12',
    'rRight_Broca_44.csv': 'Right Broca 44',
    'rRight_Broca_45.csv': 'Right Broca 45',
    'rRight_Motor_4a.csv': 'Right Motor 4a',
    'rRight_Motor_4p.csv': 'Right Motor 4p',
    'rRight_PSC_1.csv': 'Right PSC',
    'rRight_PSC_3a.csv': 'Right PSC 3a',
    'rRight_PSC_3b.csv': 'Right PSC 3b'
}

roi_names_nii = {
    'rL_AI.nii': 'Left Ant.\nInsula',	
    'rL_aMFG.nii': 'Left aMFG',
    'rL_FEF.nii': 'Left FEF',	
    'rL_IPS.nii': 'Left IPS',	
    'rL_mMFG.nii': 'Left mMFG',	
    'rL_pMFG.nii': 'Left pMFG',
    'rL_preSMA.nii': 'Left preSMA',	
    'rL_ESV.nii': 'Left ESV',
    'rR_AI.nii': 'Right Ant.\nInsula',	
    'rR_aMFG.nii': 'Right aMFG',
    'rR_FEF.nii': 'Right FEF',	
    'rR_IPS.nii': 'Right IPS',	
    'rR_mMFG.nii': 'Right mMFG',	
    'rR_pMFG.nii': 'Right pMFG',	
    'rR_preSMA.nii': 'Right preSMA',	
    'rR_ESV.nii': 'Right ESV',
    'rR_TPJ.nii': 'Right TPJ',	
    #'rR_TempP.nii': 'Right Temporal\n Pole',	
    'rR_Rsp.nii': 'Right RSP',	
    'rR_pIPL.nii': 'Right IPL',	
    'rR_PHC.nii': 'Right PHC',	
    'rR_PCC.nii': 'Right PCC',	
    'rR_LTC.nii': 'Right LTC',	
    'rR_HF.nii': 'Right HF',	
    'rR_aMPFC.nii': 'Right aMPFC',	
    'rL_TPJ.nii': 'Left TPJ',	
    #'rL_TempP.nii': 'Left Temporal\n Pole',	
    'rL_Rsp.nii': 'Left RSP',	
    'rL_pIPL.nii': 'Left pIPL',	
    'rL_PHC.nii': 'Left PHC',	
    'rL_PCC.nii': 'Left PCC',	
    'rL_LTC.nii': 'Left LTC',	
    'rL_HF.nii': 'Left HF',	
    'rL_aMPFC.nii': 'Left aMPFC',	
    'rvMPFC.nii': 'vMPFC',	
    'rdMPFC.nii': 'dMPFC',	
    'rAuditory_Te3.nii': 'Auditory Cortex',
    'rLeft_Auditory_STS1.nii': 'Left Audtry STS',
    'rLeft_Auditory_Te10.nii': 'Left Audtry Te10',
    'rLeft_Auditory_Te11.nii': 'Left Audtry Te11',
    'rLeft_Auditory_Te12.nii': 'Left Audtry 12',
    'rLeft_Broca_44.nii': 'Left Broca 44',
    'rLeft_Broca_45.nii': 'Left Broca 45',
    'rLeft_Motor_4a.nii': 'Left Motor 4a',
    'rLeft_Motor_4p.nii': 'Left Motor 4p',
    'rLeft_PSC_1.nii': 'Left PSC',
    'rLeft_PSC_3a.nii': 'Left PSC 3a',
    'rLeft_PSC_3b.nii': 'Left PSC 3b',
    'rRight_Auditory_STS1.nii': 'Right Audtry STS',
    'rRight_Auditory_Te10.nii': 'Right Audtry Te10',
    'rRight_Auditory_Te11.nii': 'Right Audtry Te11',
    'rRight_Auditory_Te12.nii': 'Right Audtry Te12',
    'rRight_Broca_44.nii': 'Right Broca 44',
    'rRight_Broca_45.nii': 'Right Broca 45',
    'rRight_Motor_4a.nii': 'Right Motor 4a',
    'rRight_Motor_4p.nii': 'Right Motor 4p',
    'rRight_PSC_1.nii': 'Right PSC',
    'rRight_PSC_3a.nii': 'Right PSC 3a',
    'rRight_PSC_3b.nii': 'Right PSC 3b'
}